import Head from "next/head";
import { Web3Button } from "@web3modal/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Web3Button />
    </div>
  );
}
